/*
 * oauth.h
 *
 * This file is part of the Socializer library
 * Copyright (C) 2012 Ispirata <info@ispirata.com>
 *
 * Author Francesco Nwokeka <francesco@ispirata.com>
 */

#ifndef OAUTH_H
#define OAUTH_H

#include <QtCore/QByteArray>
#include <QtCore/QObject>

/**
 * Class used to handle OAuth data for various services
 */

namespace Socializer
{

class OAuth : public QObject
{
    Q_OBJECT

    Q_PROPERTY(QByteArray appId READ appId WRITE setAppId)
    Q_PROPERTY(QByteArray authToken READ authToken WRITE setAuthToken)
    Q_PROPERTY(QByteArray redirectUrl READ redirectUrl WRITE setRedirectUrl)

public:
    /// TODO should redirectUrl be a needed param?
    OAuth(const QByteArray &appId, const QByteArray &redirectUrl = QByteArray(), QObject *parent = 0);
    ~OAuth();

    QByteArray appId() const;
    QByteArray authToken() const;

    /** returns url to access for authentication */
    virtual QString obtainAuthPageUrl() = 0;

    QByteArray redirectUrl() const;

    void setAppId(const QByteArray &appId);
    void setAuthToken(const QByteArray &authToken);
    void setRedirectUrl(const QByteArray &redirectUrl);

private:
//     /**
//      * Generates a unique token for a request (Twitter)
//      *
//      * The oauth_nonce parameter is a unique token your application
//      * should generate for each unique request. Twitter will use this
//      * value to determine whether a request has been submitted multiple times.
//      * The value for this request was generated by base64 encoding 32 bytes of
//      * random data, and stripping out all non-word characters, but any approach
//      * which produces a relatively random alphanumeric string should be OK here.
//      * */
//     QByteArray generateNonce();

    QByteArray m_appId;         /** id code to authenticate service to (consumerKey/clientId) */
    QByteArray m_authToken;     /** auth token recieved from service */
    QByteArray m_nonce;         /** a unique token the application should generate for each unique request (Twitter)*/
    QByteArray m_redirectUrl;   /** url to redirect after auth */
};

};


#endif  // OAUTH_H